GET http://localhost:8000/api/conference


###

POST http://localhost:8000/api/poll
Content-Type: application/json

{"name": "Опрос",
 "questions": [
   {
    "question": "Кто мы?",
    "variants": ["ОРКИ","ЛЮДИ","ЭЛЬФЫ"]
   },
   {
    "question": "За что мы?",
    "variants": ["ЗА ОРДУ"]
   },
   {
     "question": "Где мы?"
   }
 ]
}

###

DELETE http://localhost:8000/api/conference/poll

###
