POST http://localhost:8000/api/session
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"code":"1641210713"}

###

GET http://localhost:8000/api/session
Content-Type: application/json

###
