POST http://localhost:8000/api/seturl
Content-Type: application/json

{
  "url": "https://facecast.net/v/fls0ex"
}

###

POST https://airtransport-restart.ru/api/seturl
Content-Type: application/json

{
  "url": "https://facecast.net/v/fls0ex"
}

###