export const CONFERENCE_ITEMS = [
  {
    id: 0,
    image: null,
    name: 'Приветственное слово',
    speaker: '',
    description: '',
    time: '09:30 – 09:40',
  },
  {
    id: 1,
    image: '/assets/speakers/rectangle.png',
    name: '',
    speaker: 'Владимир Бусько',
    description: 'Первый Вице-Президент банка ГПБ (АО)',
    time: null,
  },
  {
    id: 1.5,
    image: null,
    name: 'Обзор изменений Федерального закона от 10.12.2003 № 173-ФЗ «О валютном регулировании и валютном контроле»',
    speaker: '',
    description: '',
    time: '09:40 - 11:00',
  },
  {
    id: 2,
    image: '/assets/speakers/shakina.png',
    name: '',
    speaker: 'Елена Шакина',
    description: 'Заместитель директора финансового мониторинга и валютного контроля Центрального банка Российской Федерации',
    time: null,
  },
  {
    id: 2.5,
    image: null,
    name: [
      'Практические вопросы сопровождения валютных операций в Банке ГПБ (АО)',
      'Личный кабинет участника ВЭД - текущие возможности и планы развития',
    ],
    speaker: '',
    description: '',
    time: '11:00 - 11:30',
  },
  {
    id: 3,
    image: '/assets/speakers/zetilova.jpg',
    name: '',
    speaker: 'Татьяна Зетилова',
    description: 'Заместитель начальника Департамента сопровождения валютных операций банка ГПБ (АО)',
    time: null,
  },
  {
    id: 3.1,
    image: '/assets/speakers/putilina.jpg',
    name: '',
    speaker: 'Юлия Путилина',
    description: 'Начальник Управления сопровождения и контроля валютных операций Департамента сопровождения валютных операций банка ГПБ (АО)',
    time: null,
  },
  {
    id: 3.2,
    image: '/assets/speakers/mironova.jpg',
    name: '',
    speaker: 'Екатерина Миронова',
    description: 'Заместитель начальника Управления сопровождения и контроля валютных операций Департамента сопровождения валютных операций банка ГПБ (АО)',
    time: null,
  },
  {
    id: 5.5,
    image: null,
    name: 'Сессия вопросов и ответов',
    speaker: '',
    description: '',
    time: '11:30 – 12:00',
  },
  {
    id: 6,
    image: '/assets/speakers/lopatnikova.jpg',
    name: '',
    speaker: 'Элина Вячеславовна',
    description: 'Вице-Президент - начальник Департамента сопровождения валютных операций банка ГПБ (АО)',
    time: null,
  },
  {
    id: 8,
    image: '/assets/speakers/zetilova.jpg',
    name: '',
    speaker: 'Татьяна Зетилова',
    description: 'Заместитель начальника Департамента сопровождения валютных операций банка ГПБ (АО)',
    time: null,
  },
  {
    id: 7,
    image: '/assets/speakers/putilina.jpg',
    name: '',
    speaker: 'Юлия Путилина',
    description: 'Начальник Управления сопровождения и контроля валютных операций Департамента сопровождения валютных операций банка ГПБ (АО)',
    time: null,
  },
  {
    id: 9,
    image: '/assets/speakers/mironova.jpg',
    name: '',
    speaker: 'Екатерина Миронова',
    description: 'Заместитель начальника Управления сопровождения и контроля валютных операций Департамента сопровождения валютных операций банка ГПБ (АО)',
    time: null,
  },
]

export const TECH_SUPPORTERS = [
  {
    name: 'Светлана Пименова',
    phone: '+7 903 263-46-14',
  },
  {
    name: 'Валерия Бурская',
    phone: '+7 965 109-30-88',
  },
  {
    name: 'Никита Качаев',
    phone: '+7 964 500-25-33',
  },
]
